const express = require('express');
const bodyparser = require('body-parser');
const cors = require('cors');
const freq = require('./Routes/freq');
const users = require('./Routes/users');
const feedback = require('./Routes/feedback');
const app = express();
app.use(cors());
app.use(bodyparser.urlencoded({ extended :  true}));
app.use(bodyparser.json());
app.use('/freq',freq);
app.use('/users',users);
app.use('/feedback',feedback);
module.exports = app;